# 389. Find the Difference

# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.

# 比较高级一点的方法是用bit manipulation的xor

from collections import Counter
class Solution:
    # 方法1：最简单的可以用counter来比较即可
    def findTheDifference(self, s, t):
        return list(Counter(t) - Counter(s))[0]

    # 方法2：unicode difference
    def findTheDifference1(self, s, t):
        diff = 0
        for i in range(len(s)):
            diff -= ord(s[i])
            diff += ord(t[i])
        diff += ord(t[-1])
        return chr(diff)

    # 方法3：unicode and xor
    def findTheDifference2(self, s, t):
        code = 0
        for ch in s + t:
            code ^= ord(ch)
        return chr(code)